import 'dart:io';

void main() {
  final file = File('lib/features/swipe/swipe_card.dart');
  var content = file.readAsStringSync();

  // Update indicator logic:
  // dx > 0 means dragging right (KEEP)
  // dx < 0 means dragging left (TRASH)
  content = content.replaceAll(
    'if (offset.dx > 0)\n                      Positioned(\n                        top: 40,\n                        left: 40,\n                        child: Transform.rotate(\n                          angle: -pi / 12,\n                          child: Opacity(\n                            opacity: (offset.dx / 100).clamp(0.0, 1.0),\n                            child: Container(\n                              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),\n                              decoration: BoxDecoration(\n                                border: Border.all(color: AppTheme.error, width: 4),\n                                borderRadius: BorderRadius.circular(8),\n                              ),\n                              child: Text(\n                                \'TRASH\',\n                                style: AppTheme.headingStyle.copyWith(color: AppTheme.error, fontSize: 32),\n                              ),\n                            ),\n                          ),\n                        ),\n                      ),',
    'if (offset.dx > 0)\n                      Positioned(\n                        top: 40,\n                        left: 40,\n                        child: Transform.rotate(\n                          angle: -pi / 12,\n                          child: Opacity(\n                            opacity: (offset.dx / 100).clamp(0.0, 1.0),\n                            child: Container(\n                              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),\n                              decoration: BoxDecoration(\n                                border: Border.all(color: AppTheme.primary, width: 4),\n                                borderRadius: BorderRadius.circular(8),\n                              ),\n                              child: Text(\n                                \'KEEP\',\n                                style: AppTheme.headingStyle.copyWith(color: AppTheme.primary, fontSize: 32),\n                              ),\n                            ),\n                          ),\n                        ),\n                      ),'
  );

  content = content.replaceAll(
    'if (offset.dx < 0)\n                      Positioned(\n                        top: 40,\n                        right: 40,\n                        child: Transform.rotate(\n                          angle: pi / 12,\n                          child: Opacity(\n                            opacity: (-offset.dx / 100).clamp(0.0, 1.0),\n                            child: Container(\n                              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),\n                              decoration: BoxDecoration(\n                                border: Border.all(color: AppTheme.primary, width: 4),\n                                borderRadius: BorderRadius.circular(8),\n                              ),\n                              child: Text(\n                                \'KEEP\',\n                                style: AppTheme.headingStyle.copyWith(color: AppTheme.primary, fontSize: 32),\n                              ),\n                            ),\n                          ),\n                        ),\n                      ),',
    'if (offset.dx < 0)\n                      Positioned(\n                        top: 40,\n                        right: 40,\n                        child: Transform.rotate(\n                          angle: pi / 12,\n                          child: Opacity(\n                            opacity: (-offset.dx / 100).clamp(0.0, 1.0),\n                            child: Container(\n                              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),\n                              decoration: BoxDecoration(\n                                border: Border.all(color: AppTheme.error, width: 4),\n                                borderRadius: BorderRadius.circular(8),\n                              ),\n                              child: Text(\n                                \'TRASH\',\n                                style: AppTheme.headingStyle.copyWith(color: AppTheme.error, fontSize: 32),\n                              ),\n                            ),\n                          ),\n                        ),\n                      ),'
  );

  file.writeAsStringSync(content);
}
